version: '3.8'

services:
  chatbot:
    build: .
    container_name: messenger_chatbot
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: catalogo_db
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_PORT: 5432
      GEMINI_API_KEY: AIzaSyDRivvwFML1GTZ_S-h5Qfx4qP3EKforMoM 
    volumes:
      - ./fb_credentials.json:/app/fb_credentials.json
      - ./catalogo_.pdf:/app/catalogo_.pdf
      - ./temp_images:/app/temp_images
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: catalogo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
