version: '3.8'

services:
  chatbot:
    build: .
    container_name: messenger_chatbot
    restart: always
    environment:
    - POSTGRES_HOST
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    - POSTGRES_PORT
    - GEMINI_API_KEY
    volumes:
      - ./fb_credentials.json:/app/fb_credentials.json
      - ./catalogo_.pdf:/app/catalogo_.pdf
      - ./temp_images:/app/temp_images
